"""Stable gameplay-domain contracts."""

from .drops import (
    MAX_ACTIVE_DROPS,
    DroppedItem,
    DroppedItemManager,
    DroppedItemSnapshot,
    PickupResult,
)
from .inventory import (
    HOTBAR_SIZE,
    INVENTORY_CAPACITY,
    InventoryAddResult,
    InventorySlot,
    PlayerInventory,
    PlayerInventorySnapshot,
    create_bootstrap_inventory,
)
from .items import (
    MAX_STACK_SIZE,
    ItemPolicy,
    ItemStack,
    ItemType,
    ToolClassification,
    ToolInstance,
    ToolTier,
    item_for_material,
    item_policy,
    material_for_item,
)
from .mining import (
    MiningSnapshot,
    MiningStatus,
    TimedMiningController,
    hardness_microseconds,
    mining_duration_microseconds,
    tool_speed_multiplier,
)
from .vitals import (
    FALL_DAMAGE_PER_BLOCK,
    JUMP_STAMINA_COST,
    MAXIMUM_HEALTH,
    MAXIMUM_STAMINA,
    MINIMUM_SPRINT_STAMINA,
    SAFE_FALL_DISTANCE_MILLI,
    SPRINT_DRAIN_PER_SECOND,
    STAMINA_REGEN_DELAY_MICROSECONDS,
    STAMINA_REGEN_PER_SECOND,
    VITAL_SCALE,
    PlayerVitals,
    PlayerVitalsSnapshot,
)

__all__ = [
    "FALL_DAMAGE_PER_BLOCK",
    "HOTBAR_SIZE",
    "INVENTORY_CAPACITY",
    "JUMP_STAMINA_COST",
    "MAXIMUM_HEALTH",
    "MAXIMUM_STAMINA",
    "MAX_ACTIVE_DROPS",
    "MAX_STACK_SIZE",
    "MINIMUM_SPRINT_STAMINA",
    "SAFE_FALL_DISTANCE_MILLI",
    "SPRINT_DRAIN_PER_SECOND",
    "STAMINA_REGEN_DELAY_MICROSECONDS",
    "STAMINA_REGEN_PER_SECOND",
    "VITAL_SCALE",
    "DroppedItem",
    "DroppedItemManager",
    "DroppedItemSnapshot",
    "InventoryAddResult",
    "InventorySlot",
    "ItemPolicy",
    "ItemStack",
    "ItemType",
    "MiningSnapshot",
    "MiningStatus",
    "PickupResult",
    "PlayerInventory",
    "PlayerInventorySnapshot",
    "PlayerVitals",
    "PlayerVitalsSnapshot",
    "TimedMiningController",
    "ToolClassification",
    "ToolInstance",
    "ToolTier",
    "create_bootstrap_inventory",
    "hardness_microseconds",
    "item_for_material",
    "item_policy",
    "material_for_item",
    "mining_duration_microseconds",
    "tool_speed_multiplier",
]
